### PR TITLE
Use 24.08 version of freedesktop-sdk

### LINKED ISSUE #29: release for 24.08 sdk?
depends on https://github.com/flathub/org.freedesktop.Sdk.Extension.node20/issues/17

### PR DESCRIPTION
**Pull request by A6GibKm**
Fixes: https://github.com/flathub/org.freedesktop.Sdk.Extension.typescript/issues/29

The contents of the MR are in line with https://github.com/flathub/org.freedesktop.Sdk.Extension.node20/pull/11.

### CODE REVIEW

**Comment by A6GibKm** [comment]
I tested that Decibel opens correctly at https://github.com/flathub/org.gnome.Decibels/pull/1

**Comment by vixalien** [comment]
lgtm ^^

**Comment by vixalien** [comment]
I think the target branch is incorrect though...

**Comment by A6GibKm** [comment]
Yes it is, but we need @BrainBlasted for creating the new branch. I just noticed that there is a [wip/cdavis/24.08beta](https://github.com/flathub/org.freedesktop.Sdk.Extension.typescript/tree/wip/cdavis/24.08beta) branch already.

**Pull request merged**
